language: cpp
dist: xenial
compiler:
  - gcc
addons:
  apt:
    packages:
      - wget
      - openssl
      - libssl-dev
      - pkg-config
      - libboost-all-dev
      - sqlite3
      - libsqlite3-dev
before_script:
  - cd /tmp && \
    wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.2.4/flyway-commandline-5.2.4-linux-x64.tar.gz | tar xvz && \
    ln -s `pwd`/flyway-5.2.4/flyway /usr/local/bin
  - cd /tmp && \
    git clone https://github.com/Microsoft/cpprestsdk && \
    cd cpprestsdk && \
    git submodule update --init -- Release/libs/websocketpp && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -DBUILD_SAMPLES=OFF && \
    make -j4 && \
    make install && \
    rm -Rf /tmp/cpprestsdk
  - cd /tmp && \
    git clone git://github.com/SOCI/soci.git && \
    mkdir soci/build && \
    cd soci/build && \
    cmake -DWITH_SQLITE3=ON DSOCI_TESTS=OFF .. && \
    make -j4 && \
    make install && \
    rm -Rf /tmp/soci
  - cd /tmp && \
    git clone https://github.com/Cylix/cpp_redis.git && \
    cd cpp_redis && \
    git submodule init && git submodule update && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make -j4 && \
    make install && \
    rm -Rf /tmp/cpp_redis
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake ..
script:
  - cmake --build . -- -j${JOBS}