language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      compiler: gcc
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/built_deps
      addons:
        apt:
          packages:
            - openssl
            - libssl-dev
            - pkg-config
            - libboost-all-dev
            - sqlite3
            - libsqlite3-dev
before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - ./scripts/build_deps.sh
  - mkdir build && cd build
  - cmake ..
script:
  - cmake --build . -- -j${JOBS}