language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/deps
          - ${TRAVIS_BUILD_DIR}/built_deps
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9
            - curl
            - unzip
            - tar
            - wget
            - build-essential
            - git
            - openssl
            - libssl-dev
            - pkg-config
before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - ./scripts/build_deps.sh
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/deps/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cd ..
script:
  - cmake --build . -- -j${JOBS}