language: bash

services:
  - docker

matrix:
  include:
    - os: linux
      dist: bionic
      script:
        - docker build -f Dockerfile_Linux -t micro-service-linux .
#    - os: windows
#      script:
#        - docker build -f Dockerfile_Windows -t micro-service-windows .