language: cpp
dist: xenial
compiler:
  - gcc
addons:
  apt:
    packages:
      - openssl
      - libcpprest-dev
      - libboost-log1.58-dev
      - libboost-program-options1.58-dev
      - sqlite3
      - libsqlite3-dev
before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake ..
script:
  - cmake --build . -- -j${JOBS}